src/Teachers/LoginNew.js
src/Teachers/Teams/CreateTeam.js
src/Teachers/Teams/EditTeamMember.jsx
src/Teachers/Teams/Ticket.jsx
src/Teachers/Teams/ViewTeamMember.js

Team Creation

---

src/Admin/UserList/TeacherRegister.js
src/RegPage/AtlPage.js
src/RegPage/NonAtlPage.js

Registration Flow

---

src/RegPage/SuccesScreen.jsx
src/RegPage/SuccessNew.js
src/Teachers/MyProfile.js
src/Teachers/Teams/CreateTeam.js
src/Teachers/Teams/CreateTeamMember.jsx
src/redux/studentRegistration/actions.js

Bugs fixed

---

public/assets/locales/te/translation.json
src/Teachers/Teams/EditTeamMember.jsx

Validation

---

public/assets/locales/hi/translation.json
public/assets/locales/ka/translation.json
src/Admin/Challenges/ViewSelectedChallenges.jsx
src/Admin/Dashboard/ViewMore.js
src/Admin/Dashboard/index.jsx
src/Admin/Schools/Ticket.jsx
src/Admin/Tickets/Ticket.jsx
src/Admin/UserList/TacherViewDetails.js
src/Student/Pages/Courses/PlayVideo.jsx
src/Student/Pages/Ideas/InstuctionsPage.js

New Tickets

---

src/Admin/Challenges/ViewDetail.jsx
src/Admin/Challenges/ViewSelectedChallenges.jsx
src/Admin/Reports/Helpers/ReportsRegistration.jsx
src/Admin/Reports/Helpers/TeacherProgressDetailed.jsx
src/Evaluator/Admin/Challenges/ViewDetail.jsx
src/Evaluator/Admin/Challenges/ViewSelectedChallenges.jsx
src/Evaluator/Admin/Evaluation/FinalResults/ViewFinalDetail.jsx
src/Evaluator/Admin/Evaluation/FinalResults/ViewFinalSelectedideas.jsx
src/Evaluator/Admin/Evaluation/ViewSelectedIdea/ViewDetail.jsx
src/Evaluator/Admin/Evaluation/ViewSelectedIdea/ViewSelectedideas.jsx
src/Evaluator/EvaluatedIdea/EvaluatedIdea.jsx
src/Evaluator/EvaluatedIdea/EvaluatedIdeaL2.jsx

State Filters

---

src/Admin/UserList/Ticket.jsx
src/Evaluator/Admin/Evaluator/EadminEditProfile.js
src/Evaluator/Admin/Evaluator/EadminEvaluator.js
src/Evaluator/LoginEvaluator.jsx
src/Evaluator/Register.jsx

Add Evaluator

---

src/Admin/Challenges/TableDetailPdf.jsx
src/Admin/Challenges/ViewDetail.jsx
src/Admin/Challenges/ViewSelectedChallenges.jsx
src/Admin/Evaluation/FinalResults/DetailToDownload.jsx
src/Admin/Evaluation/FinalResults/TableDetailPdf.jsx
src/Admin/Evaluation/FinalResults/ViewFinalDetail.jsx
src/Evaluator/Admin/Challenges/ViewDetail.jsx
src/Evaluator/Admin/Challenges/ViewSelectedChallenges.jsx
src/Evaluator/Admin/Evaluation/FinalResults/ViewFinalDetail.jsx
src/Evaluator/Admin/Evaluation/FinalResults/ViewFinalSelectedideas.jsx
src/Evaluator/Admin/Evaluation/ViewSelectedIdea/ViewDetail.jsx
src/Evaluator/Admin/Evaluation/ViewSelectedIdea/ViewSelectedideas.jsx
src/Evaluator/Admin/Pages/ReasonForRejectionData.js
src/Evaluator/EvaluatedIdea/EvaluatedIdea.jsx
src/Evaluator/EvaluatedIdea/EvaluatedIdeaDetail.jsx
src/Evaluator/EvaluatedIdea/EvaluatedIdeaL2.jsx
src/Evaluator/IdeaList/IdeaDetail.jsx
src/Evaluator/IdeaList/NextLevel.js

Evaluator pannel

---

src/Coordinators/Aside.js
src/Coordinators/ChangePswModal.js
src/Coordinators/Dashboard/index.js
src/Coordinators/LogInNew.js
src/ReportsPanel/LoginReport.js
src/Routes.js
src/Teachers/Teams/CreateTeamMember.jsx
src/Teachers/Teams/EditTeamMember.jsx
src/constants/defaultValues.js

State login

---

src/Admin/UserList/CommonUserProfile.js
src/Coordinators/Aside.js
src/Coordinators/Reports/CoRegReport.js
src/Coordinators/Reports/CoTeacherDetailedReport.js
src/Coordinators/Reports/CostudentDetailedReport.js
src/Coordinators/UsersList/AtlReg.js
src/Coordinators/UsersList/CommonUserProfile.js
src/Coordinators/UsersList/CooTecDashoard.js
src/Coordinators/UsersList/MentorEditProfile.js
src/Coordinators/UsersList/NonAtlReg.js
src/Coordinators/UsersList/StudentEditProfile.js
src/Coordinators/UsersList/SuccessAtl.js
src/Coordinators/UsersList/SuccessNonAtl.js
src/Coordinators/UsersList/TeacReg.js
src/Coordinators/UsersList/TeacView.js
src/Coordinators/UsersList/UsersData.js
src/Routes.js

Add On Feature in State panel

---

src/Admin/Tickets/Ticket.jsx
src/Coordinators/Dashboard/index.js
src/Coordinators/Header.js

Dashboard data

---

src/Coordinators/Aside.js
src/Coordinators/CooChallenges/CoDetailToDown.jsx
src/Coordinators/CooChallenges/CoViewSelectedChallenges.jsx
src/Coordinators/CooChallenges/ViewDetail.js
src/Coordinators/Reports/CoRegReport.js
src/Coordinators/Reports/CoTeacherDetailedReport.js
src/Coordinators/Reports/CostudentDetailedReport.js
src/Coordinators/UsersList/UsersData.js
src/Routes.js

Challenges

---

src/Admin/Reports/Helpers/IdeasDetailsReport.js
src/Admin/Reports/index.jsx
src/Evaluator/Admin/Evaluation/ViewSelectedIdea/ViewSelectedideas.jsx
src/Evaluator/Admin/Pages/Aside.js
src/Evaluator/Admin/Reports/ReportL1.js
src/Evaluator/Admin/Reports/ReportL2.jsx
src/Evaluator/Admin/Reports/ReportL3.js
src/Evaluator/Admin/Reports/index.js
src/Routes.js

Eadmin reports

---

src/Coordinators/Aside.js
src/Coordinators/CooTickets/TicketResponse.js
src/Coordinators/CooTickets/Tickets.js
src/Routes.js
src/Teachers/SupportJourney/AddNewTicket.jsx

 Support Tickets

---

src/Evaluator/Admin/Evaluation/FinalResults/ViewFinalSelectedideas.jsx
src/Evaluator/Register.jsx

Eadmin Validations

---

src/RegPage/FirstPage.js

 Text Changes

---

src/Coordinators/Dashboard/CoDoughnutChart.jsx
src/Evaluator/Admin/Challenges/ViewSelectedChallenges.jsx
src/Evaluator/Admin/Evaluation/FinalResults/ViewFinalSelectedideas.jsx
src/Evaluator/Admin/Evaluation/ViewSelectedIdea/ViewSelectedideas.jsx
src/Evaluator/Admin/Reports/ReportL1.js
src/Teachers/Dashboard/DoughnutChart.jsx

New Changes

---

src/Coordinators/Dashboard/CoDoughnutChart.jsx
src/Evaluator/Admin/Challenges/ViewSelectedChallenges.jsx
src/Evaluator/Admin/Evaluation/FinalResults/ViewFinalSelectedideas.jsx
src/Evaluator/Admin/Evaluation/ViewSelectedIdea/ViewSelectedideas.jsx
src/Evaluator/Admin/Reports/ReportL1.js
src/RegPage/FirstPage.js
src/Teachers/Dashboard/DoughnutChart.jsx

 Fe Dev to Stage 

---

src/Admin/Reports/Helpers/StudentsProgressReport.jsx

state Value

---

.htaccess

Reverts Inqui-Lab-Foundation/aim_fe#98

Revert "cache 1"

---

src/Admin/LoginNew.js
src/Admin/Schools/AddNewSchool.jsx
src/Admin/Schools/EditSchool.js
src/Admin/UserList/AddAdmins.jsx
src/Admin/UserList/EditProfile.js
src/Admin/UserList/NonAtlReg.jsx
src/Coordinators/LogInNew.js
src/Evaluator/Admin/EvaluatorAdminLogin.jsx
src/Evaluator/LoginEvaluator.jsx
src/RegPage/AtlPage.js
src/RegPage/NonAtlPage.js
src/Student/Pages/LoginNew.js
src/Teachers/EditTeacherProfile.js
src/Teachers/LoginNew.js
src/Teachers/Teams/CreateTeam.js
src/Teachers/Teams/EditTeam.jsx
src/Teachers/Teams/EditTeamMember.jsx

validations

---

src/Admin/Schools/AddNewSchool.jsx
src/Evaluator/Register.jsx

evaluator validation

---

.htaccess
src/Admin/Schools/AddNewSchool.jsx
src/Evaluator/Register.jsx

Dev to stage

---

src/Admin/Schools/EditSchool.js
src/Admin/Schools/Select.jsx
src/Admin/UserList/Ticket.jsx
src/Coordinators/Dashboard/index.js
src/Coordinators/UsersList/CooTecDashoard.js
src/Evaluator/Admin/Evaluator/EadminEvaluator.js

NewChanges
